export const symbols = [
  ["template", "지우개"],
  ["knit", "겉뜨기"],
  ["purl", "안뜨기"],
  ["bindoff", "코막음 (BO)"],
  ["yarnover", "바늘비우기 (YO)"],
  ["decreaseright", "k2tog (오른기울 2코 모아)"],
  ["decreaseleft", "SSK (왼기울 2코 모아)"],
  ["increaseright", "M1R (오른쪽 늘림)"],
  ["increaseleft", "M1L (왼쪽 늘림)"],
  ["decreaseleft_purl", "SSP (왼기울 2코 모아 안뜨기)"],
  ["decreaseright_purl", "p2tog (오른기울 2코 모아 안뜨기)"],
  ["decrease3to1centered", "중심 3코 모아뜨기"],
  ["decrease3to1right", "오른쪽 3코 모아뜨기"],
  ["decrease3to1left", "왼쪽 3코 모아뜨기"],
  ["template", "--------------"],
  ["slip", "빼뜨기 – 실 뒤"],
  ["slipwyif", "빼뜨기 – 실 앞"],
  ["nostitch", "빈칸 (No stitch)"],
  ["increase1to3", "감아코 (1→3 늘림)"],
  ["twist", "꼬아뜨기 (ktbl)"],
  ["twist_purl", "꼬아 안뜨기 (ptbl)"],
  ["passright", "오른코 덮어씌우기"],
  ["passleft", "왼코 덮어씌우기"],
  ["crossleft", "교차 → 왼쪽으로"],
  ["crossright", "교차 → 오른쪽으로"],
  ["crossleft_purl", "교차(왼) + 안뜨기"],
  ["crossright_purl", "교차(오) + 안뜨기"],
  ["decrease4to1right", "오른쪽 4코 모아뜨기"],
  ["decrease4to1left", "왼쪽 4코 모아뜨기"],
  ["decrease5to1centered", "중심 5코 모아뜨기"],
  ["decrease5to1right", "오른쪽 5코 모아뜨기"],
  ["decrease5to1left", "왼쪽 5코 모아뜨기"],
  ["decreaseleft.2w", "SSK (두 칸 폭)"],
  ["decreaseright.2w", "k2tog (두 칸 폭)"],
  ["c2over1right", "2↘1 꽈배기 (오른앞)"],
  ["c2over1left", "2↖1 꽈배기 (왼앞)"],
  ["c2over2right", "2↘2 꽈배기 (오른앞)"],
  ["c2over2left", "2↖2 꽈배기 (왼앞)"],
  ["diptwist", "꼬아 딥스티치"],
  ["dip", "딥스티치"],
  ["yarnovertwist", "꼬아 바늘비우기"],
  ["slantleft", "왼쪽 단일 경사"],
  ["slantright", "오른쪽 단일 경사"],
  ["twistleft", "트위스트 ↖"],
  ["twistright", "트위스트 ↘"],
  ["twistleft_purl", "트위스트 ↖ + 안뜨기"],
  ["twistright_purl", "트위스트 ↘ + 안뜨기"],
  ["decrease6to1right", "오른쪽 6코 모아뜨기"],
  ["decrease6to1left", "왼쪽 6코 모아뜨기"],
  ["decrease7to1", "중심 7코 모아뜨기"],
  ["decrease7to1right", "오른쪽 7코 모아뜨기"],
  ["decrease7to1left", "왼쪽 7코 모아뜨기"],
  ["c2over1right-purl", "2↘1 꽈배기 + 안뜨기"],
  ["c2over1left-purl", "2↖1 꽈배기 + 안뜨기"],
  ["c2over2right-purl", "2↘2 꽈배기 + 안뜨기"],
  ["c2over2left-purl", "2↖2 꽈배기 + 안뜨기"],
  ["dip_purl", "딥스티치 안뜨기"],
  ["template", "템플릿 (1칸)"],
  ["template.2w", "템플릿 – 2칸"],
  ["template.3w", "템플릿 – 3칸"],
  ["template.4w", "템플릿 – 4칸"],
  ["template.2h", "템플릿 – 2줄"],
  ["twist.straight", "꼬아뜨기 (직선 변형)"],
];
